#!/usr/bin/env python3
"""Measure which surnames the game's commentary can say, and with what id.

The Player table carries a ``PLYR_COMMENT`` field: an index into the
commentary audio, which is what lets the announcers say a player's name out
loud. A recreated player left at whatever the replaced player had would be
called by somebody else's name, and one set to 0 is simply never named.

Nothing here is invented. The mapping is read out of dynasty saves the *game
itself* generated, where the game assigned both the surname and the id. Saves
whose rosters were hand-edited are deliberately not read: a roster editor can
leave ``PLYR_COMMENT`` pointing at the previous occupant of a slot, so a
renamed player pairs a new surname with a stale id. Feeding that back in would
teach this file a name the announcers cannot actually say.

    python3 tools/build_commentary_ids.py <export-dir> [<export-dir> ...] \
        --out data/CommentaryIds.json

Each <export-dir> is a folder holding a ``0152_Player.csv`` (or any Player
table export); pass as many as you have. More saves is strictly better, since
a surname absent from one save may be present in another.
"""
import argparse
import collections
import csv
import json
import pathlib
import sys

csv.field_size_limit(10**9)


def player_tables(root: pathlib.Path):
    """Every Player table under a folder, or the file itself."""
    if root.is_file():
        return [root]
    return sorted(root.rglob("*Player.csv"))


def read(path: pathlib.Path, counts, rows):
    with path.open(newline="", encoding="utf-8", errors="replace") as handle:
        reader = csv.reader(handle)
        header = next(reader)
        for column in ("LastName", "PLYR_COMMENT"):
            if column not in header:
                return 0
        last = header.index("LastName")
        comment = header.index("PLYR_COMMENT")
        empty = header.index("_isEmpty") if "_isEmpty" in header else None

        seen = 0
        for row in reader:
            if empty is not None and row[empty].strip().lower() == "true":
                continue
            name = row[last].strip()
            if not name:
                continue
            counts[name][row[comment].strip()] += 1
            seen += 1
        rows[0] += seen
        return seen


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("exports", nargs="+", type=pathlib.Path)
    parser.add_argument("--out", type=pathlib.Path, required=True)
    args = parser.parse_args()

    counts = collections.defaultdict(collections.Counter)
    rows = [0]
    sources = []
    for export in args.exports:
        for table in player_tables(export):
            seen = read(table, counts, rows)
            if seen:
                sources.append(str(table))
                print(f"  {seen:>6,} players  {table}", file=sys.stderr)

    if not sources:
        sys.exit("No Player tables with a PLYR_COMMENT column were found.")

    mapping = {}
    ambiguous = {}
    for name, seen in counts.items():
        # 0 means "the announcers do not say this player's name". A surname
        # seen at both 0 and a real id still has a real id available, so the
        # real one wins: the name IS sayable.
        options = {value: n for value, n in seen.items() if value != "0"}
        if not options:
            continue

        best = max(options, key=lambda value: options[value])
        mapping[name] = int(best)
        if len(options) > 1:
            ambiguous[name] = {value: options[value] for value in sorted(options)}

    document = {
        "_comment": (
            "Surname -> PLYR_COMMENT, measured from dynasty saves the game itself "
            "generated. A surname absent from this file gets 0, which is the game's "
            "own value for a player the commentary never names. Generated by "
            "tools/build_commentary_ids.py; edit that, or the saves you feed it, "
            "rather than this."
        ),
        "playersRead": rows[0],
        "sourceCount": len(sources),
        "surnamesWithId": len(mapping),
        "surnamesWithoutId": len(counts) - len(mapping),
        "ambiguous": ambiguous,
        "byLastName": dict(sorted(mapping.items())),
    }

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(json.dumps(document, indent=1) + "\n")

    print(
        f"\n{rows[0]:,} players from {len(sources)} table(s)\n"
        f"{len(mapping):,} surnames have a commentary id, "
        f"{len(counts) - len(mapping):,} have none\n"
        f"{len(ambiguous)} ambiguous (more than one non-zero id): "
        f"{', '.join(sorted(ambiguous)) or 'none'}\n"
        f"written to {args.out}",
        file=sys.stderr,
    )


if __name__ == "__main__":
    main()
