using RosterGenerator.Core.Model;
using RosterGenerator.Core.Schema;

namespace RosterGenerator.Core.Editing;

/// <summary>
/// The supported way to modify a roster. Each operation applies the full set
/// of companion-field updates the save format requires (confirmed by diffing
/// real edits) and records an <see cref="EditRecord"/> declaring its intent,
/// which the validation layer then cross-checks against the actual cell
/// changes. Editing player cells directly via <see cref="Player.SetRaw"/>
/// still works but leaves no intent record, so identity or team changes made
/// that way are reported as validation errors.
/// </summary>
public sealed class RosterEditSession
{
    private readonly List<EditRecord> _edits = new();

    /// <summary>Creates an edit session over a loaded roster.</summary>
    public RosterEditSession(PlayerRoster roster)
    {
        Roster = roster;
    }

    /// <summary>The roster being edited.</summary>
    public PlayerRoster Roster { get; }

    /// <summary>All operations recorded so far, in order.</summary>
    public IReadOnlyList<EditRecord> Edits => _edits;

    /// <summary>
    /// Cosmetic rename: changes the name text only. Identity assets
    /// (portrait/head model) are deliberately left untouched, matching
    /// observed in-game rename behavior.
    /// </summary>
    public void RenamePlayer(Player player, string firstName, string lastName)
    {
        ArgumentException.ThrowIfNullOrEmpty(firstName);
        ArgumentException.ThrowIfNullOrEmpty(lastName);
        var before = player.ToString();
        player.FirstName = firstName;
        player.LastName = lastName;
        Record(player, EditIntent.Rename, $"Renamed {before} to {firstName} {lastName}");
    }

    /// <summary>
    /// Replaces the slot's identity with a different real person. The caller
    /// must supply the new identity-asset values explicitly — there is no
    /// safe way to derive them (asset names are generated by EA tooling), so
    /// forcing them into the signature keeps the "replace" contract honest.
    /// </summary>
    /// <param name="player">The roster slot being replaced.</param>
    /// <param name="firstName">New first name.</param>
    /// <param name="lastName">New last name.</param>
    /// <param name="assetName">New <c>PLYR_ASSETNAME</c> value.</param>
    /// <param name="genericHeadAssetName">New <c>GenericHeadAssetName</c> value.</param>
    /// <param name="portrait">New <c>PLYR_PORTRAIT</c> value.</param>
    public void ReplacePlayerIdentity(
        Player player,
        string firstName,
        string lastName,
        string assetName,
        string genericHeadAssetName,
        string portrait)
    {
        ArgumentException.ThrowIfNullOrEmpty(firstName);
        ArgumentException.ThrowIfNullOrEmpty(lastName);
        ArgumentNullException.ThrowIfNull(assetName);
        ArgumentNullException.ThrowIfNull(genericHeadAssetName);
        ArgumentNullException.ThrowIfNull(portrait);

        var before = player.ToString();
        player.FirstName = firstName;
        player.LastName = lastName;
        player.SetRaw(PlayerColumns.AssetName, assetName);
        player.SetRaw(PlayerColumns.GenericHeadAssetName, genericHeadAssetName);
        player.SetRaw(PlayerColumns.Portrait, portrait);
        Record(player, EditIntent.ReplaceIdentity, $"Replaced {before} with {firstName} {lastName}");
    }

    /// <summary>
    /// Moves the player to another team, applying every companion update the
    /// format requires: <c>PrevTeamIndex</c> and <c>PLYR_PREVTEAMID</c> are
    /// set to the old team, and both NIL fields are zeroed (both behaviors
    /// confirmed in real transfer edits).
    /// </summary>
    public void TransferPlayer(Player player, int newTeamIndex)
    {
        if (newTeamIndex is < 0 or > PlayerSchema.NoTeamSentinel)
        {
            throw new ArgumentOutOfRangeException(nameof(newTeamIndex),
                $"Team index must be 0–{PlayerSchema.NoTeamSentinel}.");
        }

        var oldTeamIndex = player.TeamIndex;
        if (oldTeamIndex == newTeamIndex)
        {
            return;
        }

        player.SetRaw(PlayerColumns.TeamIndex, newTeamIndex.ToString());
        player.SetRaw(PlayerColumns.PrevTeamIndex, oldTeamIndex.ToString());
        player.SetRaw(PlayerColumns.PrevTeamId, oldTeamIndex.ToString());
        player.SetRaw(PlayerColumns.BaseNilValue, "0");
        player.SetRaw(PlayerColumns.CurrentNilCompensation, "0");
        Record(player, EditIntent.Transfer, $"Transferred {player} from team {oldTeamIndex} to team {newTeamIndex}");
    }

    /// <summary>Sets the jersey number (validated later against 0–99).</summary>
    public void SetJerseyNumber(Player player, int jerseyNumber)
    {
        player.JerseyNumber = jerseyNumber;
        Record(player, EditIntent.AttributeChange, $"Set jersey number of {player} to {jerseyNumber}");
    }

    /// <summary>Sets height in raw inches.</summary>
    public void SetHeight(Player player, int heightInches)
    {
        player.HeightInches = heightInches;
        Record(player, EditIntent.AttributeChange, $"Set height of {player} to {heightInches}\"");
    }

    /// <summary>
    /// Sets weight in real pounds (160–400 lb; the save stores pounds − 160).
    /// </summary>
    public void SetWeightPounds(Player player, int weightPounds)
    {
        player.WeightPounds = weightPounds;
        Record(player, EditIntent.AttributeChange, $"Set weight of {player} to {weightPounds} lb");
    }

    /// <summary>Sets the class standing (Freshman/Sophomore/Junior/Senior).</summary>
    public void SetSchoolYear(Player player, string schoolYear)
    {
        player.SchoolYear = schoolYear;
        Record(player, EditIntent.AttributeChange, $"Set school year of {player} to {schoolYear}");
    }

    /// <summary>Sets the redshirt status (Eligible/Previous/Ineligible).</summary>
    public void SetRedshirtStatus(Player player, string redshirtStatus)
    {
        player.RedshirtStatus = redshirtStatus;
        Record(player, EditIntent.AttributeChange, $"Set redshirt status of {player} to {redshirtStatus}");
    }

    /// <summary>
    /// Sets the home town (free text) and home state (51-value enum).
    /// </summary>
    public void SetHometown(Player player, string town, string state)
    {
        if (!PlayerSchema.HomeStates.Contains(state))
        {
            throw new ArgumentException(
                $"'{state}' is not a valid PLYR_HOME_STATE value. Use a US state in the save's spelling " +
                $"(e.g. WestVirginia) or {PlayerSchema.NonUsHomeState}.", nameof(state));
        }

        player.SetRaw(PlayerColumns.HomeTown, town);
        player.SetRaw(PlayerColumns.HomeState, state);
        Record(player, EditIntent.AttributeChange, $"Set hometown of {player} to {town}, {state}");
    }

    /// <summary>
    /// Sets the player archetype. The caller MUST recompute the overall
    /// rating afterwards: the archetype selects which of EA's overall
    /// formulas applies, so leaving the old overall in place makes the record
    /// inconsistent (the defect seen in manually edited saves).
    /// </summary>
    public void SetPlayerType(Player player, string playerType)
    {
        ArgumentException.ThrowIfNullOrEmpty(playerType);
        player.SetRaw(PlayerColumns.PlayerType, playerType);
        Record(player, EditIntent.AttributeChange, $"Set archetype of {player} to {playerType}");
    }

    /// <summary>Sets the position abbreviation.</summary>
    public void SetPosition(Player player, string position)
    {
        player.Position = position;
        Record(player, EditIntent.AttributeChange, $"Set position of {player} to {position}");
    }

    /// <summary>
    /// Writes a complete generated rating set, recorded as a single edit.
    /// Unknown column names are ignored so a future model can add attributes
    /// without breaking older saves.
    /// </summary>
    public void SetGeneratedRatings(Player player, IReadOnlyDictionary<string, int> ratings, int overall)
    {
        foreach (var (column, value) in ratings)
        {
            if (PlayerSchema.NumericRatingColumns.Contains(column))
            {
                player.SetRaw(column, value.ToString());
            }
        }

        player.SetRaw(PlayerColumns.OverallRating, overall.ToString());
        Record(player, EditIntent.AttributeChange, $"Generated {ratings.Count} ratings for {player} (OVR {overall})");
    }

    /// <summary>Sets one numeric rating column.</summary>
    public void SetRating(Player player, string ratingColumn, int value)
    {
        player.SetRating(ratingColumn, value);
        Record(player, EditIntent.AttributeChange, $"Set {ratingColumn} of {player} to {value}");
    }

    /// <summary>True if any recorded edit for the row declared the given intent.</summary>
    public bool HasIntent(int rowKey, EditIntent intent) =>
        _edits.Any(e => e.RowKey == rowKey && e.Intent == intent);

    private void Record(Player player, EditIntent intent, string description) =>
        _edits.Add(new EditRecord(player.RowKey, intent, description));
}
